### ISSUE TITLE
EfficientNet torch.save error "not << overloading definition"

### ISSUE THREAD

**Issue by ingbeeedd** [crim-ca/crim-libtorch-extensions#1]
Is it right when it's used in torch.save?

**Comment by fmigneault** [comment]
Is is possible to provide more details?
I'm not sure I understand what error you encounter.

**Comment by ingbeeedd** [comment]
below code

```cpp
std::unique_ptr<vision::models::EfficientNetB0> net = std::make_unique<vision::models::EfficientNetB0>(num_classes);
torch::save(net.get(), "my_net.pt");
```
![image](https://user-images.githubusercontent.com/57895472/147033093-f21531fb-4b36-4810-9ebc-332088d6bbdb.png)

Thank you

**Comment by ingbeeedd** [comment]
I did not make it dll. Because I will use EfficientNet only, but I put only the necessary parts into the source code and tested cifar10 Is it a part where problems can occur because I do not make dll separately?

**Comment by fmigneault** [comment]
It works using the following:

```cpp
auto net = torch::nn::AnyModule(vision::models::EfficientNetB0(10));
torch::save(net.ptr(), "/tmp/net.pt");
```

I cannot validate on a Windows environment on my side, but I imagine it should also work.

**Comment by ingbeeedd** [comment]
Thank you ! 
You say I have to wrap it around AnyModule to inherit and use overloading (<<) (including the forward function). ?

**Comment by fmigneault** [comment]
Yes. Using `AnyModule` and `.prtr()` returns a shared pointer to `Module`, similarly to your original one, but it provides the missing functions with polymorphism for the referred model.
